# Generated by Django 5.2.7 on 2025-11-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_news_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views_count',
        ),
    ]
